config/routes.rb
Tinytrip::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  get "/geocode/:addresses" => "geocode#search"
  get "/directions/:points" => "directions#index"

  resources :trips do
  	resources :nodes
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :title, :address, :city, :state, :lat, :lon
  has_one :ending_node, class_name: "Node", foreign_key: 'end_location_id'
  has_one :starting_node, class_name: "Node", foreign_key: 'start_location_id'
end

app/models/node.rb
class Node < ActiveRecord::Base
  	attr_accessible :trip_id, :node_type, :position, :title, :duration, :distance, :polyline, :starts_on
	belongs_to :trip
	belongs_to :start_location, :class_name => "Location"
	belongs_to :end_location, :class_name => "Location"
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :nodes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
	def index
		points = params[:points].split '|'

		if points.count < 2
			render :json => { :success => false, :message => "At least two points are required for directions." }
			return
		end

		points.map! { |point| URI::encode_www_form_component point }

		origin = points[0]
		destination = points[points.count - 1]
		waypoints = ""
		if points.count > 2
			points.slice! 0
			points.slice! -1
			waypoints = points.join "|"
		end

		url = "http://maps.googleapis.com/maps/api/directions/json?origin=#{origin}&destination=#{destination}&waypoints=#{waypoints}&sensor=false"
		logger.info url
		resp = Curl.get url

		render :json => resp.body_str
	end
end

app/controllers/geocode_controller.rb
class GeocodeController < ApplicationController
	def search
		addresses = params[:addresses].split '-'
		addresses.map! { |address| URI::encode_www_form_component address }

		start_url = "http://maps.googleapis.com/maps/api/geocode/json?address=#{addresses[0]}&sensor=false"
		end_url = "http://maps.googleapis.com/maps/api/geocode/json?address=#{addresses[1]}&sensor=false"
		
		start_resp = Curl.get start_url
		end_resp = Curl.get end_url

		start_obj = ActiveSupport::JSON.decode(start_resp.body_str)
		end_obj = ActiveSupport::JSON.decode(end_resp.body_str)

		render :json => { :start_resp => start_obj, :end_resp => end_obj }
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
	def index
		nodes = Node.includes(:start_location, :end_location).where("trip_id = ?", params[:trip_id]).order("position")

		render :json => { :nodes => nodes }.to_json(:include => [:start_location, :end_location])
	end

	def create
		start_location = Location.create(start_location_params)
		end_location = Location.create(end_location_params)

		node = Node.create(node_params)
		node.start_location = start_location
		node.end_location = end_location
		node.save

		render :json => node.to_json(:include => [:start_location, :end_location])
	end

	def update
		node = Node.where("id = ?", params[:id]).first

		if(params[:starts_on] != nil)
			node.starts_on = params[:starts_on]
			node.save
		end

		render :json => node.to_json(:include => [:start_location, :end_location])
	end

	def destroy
		node = Node.where("id = ?", params[:id]).first

		trip_id = node.trip_id

		if(node != nil)
			node.start_location.destroy if node.start_location
			node.end_location.destroy if node.end_location
			node.destroy
		end

		# reorder remaining node positions
		nodes = Node.where("trip_id = ?", trip_id).order("position")

		for i in 0..nodes.count-1
			nodes[i].position = (i + 1)
			nodes[i].save
		end

		render :json => { :success => true }
	end

	private
	def node_params
		params.permit(:trip_id, :position, :node_type, :title, :starts_on, :duration, :distance, :polyline)
	end

	def start_location_params
		{
			:title => params[:start_title],
			:address => params[:start_address],
			:city => params[:start_city],
			:state => params[:start_state],
			:lat => params[:start_lat],
			:lon => params[:start_lon]	
		}
	end

	def end_location_params
		{
			:title => params[:end_title],
			:address => params[:end_address],
			:city => params[:end_city],
			:state => params[:end_state],
			:lat => params[:end_lat],
			:lon => params[:end_lon]	
		}
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	def new
	end

	def create
		trip = Trip.new
		trip.title = params[:title]
		trip.user_id = params[:user_id]
		trip.save

		redirect_to trip_url(trip)
	end

	def show
		@trip = Trip.where("id = ?", params[:id]).first

		@nodes = Node.where("trip_id = ?", @trip.id).order("position")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/geocode_helper.rb
module GeocodeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.erb
<div id="home" class="hero-unit">
	<h1>Welcome to TinyTrip</h1>

	<%= link_to "Start a New Trip", new_trip_url, { :class => "btn btn-primary" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TinyTrip</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<div id="container">
		<header id="header" class="navbar">
			<div class="navbar-inner">
				<div class="container-fluid">
					<a href="/" class="brand">TinyTrip<span>alpha</span></a>
				</div>
			</div>
		</header>
		<div id="content" class="container-fluid">
			<div id="content-inner" class="row-fluid">
				<%= yield %>
			</div>
		</div>
	</div>
	<%= javascript_include_tag "application" %>
	<%= yield :js %>
</body>
</html>

app/views/trips/new.html.erb
<div id="new-trip">
	<form class="form-stacked" method="POST" action="/trips">
		<input type="hidden" id="user_id" name="user_id" value="<%=current_user[:id] %>" />
		<div class="control-group">
			<label for="title" class="control-label">Trip Name</label>
			<div class="controls">
				<input type="text" id="title" name="title" class="input-large" required />
			</div>
		</div>
		<div class="form-actions">
			<button class="btn btn-primary">Add Trip</button> 
			<%= link_to "Cancel", root_url %>
		</div>
	</form>
</div>

app/views/trips/show.html.erb
<div id="trip" data-id="<%= @trip.id %>">
	<h1><%= @trip[:title] %></h1>

	<div class="row-fluid fixed-container">
		<div class="span4">
			<ul id="trip-nodes" class="unstyled trip-nodes"></ul>
			<div class="well">
				<h4>Add a leg to your journey.</h4>
				<form id="trip-nodes-new" class="form-horizontal">
					<ul class="unstyled">
						<li class="control-group">
							<label class="control-label" for="address-start">Leaving From</label>
							<div class="controls">
								<input type="text" id="address-start" class="input-large" required />
							</div>
						</li>
						<li class="control-group">
							<label class="control-label" for="address-end">Going To</label>
							<div class="controls">
								<input type="text" id="address-end" class="input-large" required />
							</div>
						</li>
						<li class="control-group">
							<label class="control-label" for="node-type">Travel Type</label>
							<div class="controls">
								<select id="node-type" name="node_type">
									<option value="drive">Drive</option>
									<option value="fly">Fly</option>
								</select>
							</div>
						</li>
						<li class="control-group">
							<label class="control-label" for="starts_on">Travel Date</label>
							<div class="controls">
								<input type="date" id="starts-on" name="starts_on" class="input-small" required />
							</div>
						</li>
					</ul>
					<div class="form-actions">
						<button id="trip-nodes-new-btn" class="btn btn-primary">Add</button>
					</div>
				</form>
			</div>
		</div>
		<div class="span8 trip-widgets">
			<div class="row-fluid">
				<div class="span6">
					<div id="trip-map" class="map">
						<div id="trip-map-inner" class="map-inner">
						</div>
					</div>
				</div>
				<div class="span6">
					<div id="trip-cal" class="cal">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<% content_for :js do %>
	<script src="http://maps.googleapis.com/maps/api/js?libraries=geometry&sensor=false"></script>
	<script>
		$(function() {
			TinyTrip.Manager({
				components: {
					trip: TinyTrip.Trips(),
					map: TinyTrip.Map({ id:'trip-map' }),
					cal: TinyTrip.Calendar({ id:'trip-cal' })
				}
			}).init();
		});
	</script>
<% end %>